// <auto-generated />
using System;
using EternalPeace.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EternalPeace.Migrations
{
    [DbContext(typeof(EternalPeaceDbContext))]
    [Migration("20250516123504_ChangeModels")]
    partial class ChangeModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EternalPeace.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Speciallity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1986, 7, 3),
                            Name = "Терехов Александр Александрович",
                            Sex = "Мужчина",
                            Speciallity = "Кардиолог",
                            WorkExperience = 12
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1992, 5, 8),
                            Name = "Киселева Валерия Ивановна",
                            Sex = "Женщина",
                            Speciallity = "Гастроэнтеролог",
                            WorkExperience = 6
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1993, 1, 14),
                            Name = "Титова Арина Денисовна",
                            Sex = "Женщина",
                            Speciallity = "Нефролог",
                            WorkExperience = 5
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(1981, 11, 27),
                            Name = "Маслов Ян Глебович",
                            Sex = "Мужчина",
                            Speciallity = "Гепатолог",
                            WorkExperience = 15
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(1988, 3, 25),
                            Name = "Назарова София Юрьевна",
                            Sex = "Женщина",
                            Speciallity = "Кардиолог",
                            WorkExperience = 9
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(1977, 3, 25),
                            Name = "Смирнов Максим Максимович",
                            Sex = "Мужчина",
                            Speciallity = "Нефролог",
                            WorkExperience = 20
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateOnly(1989, 11, 3),
                            Name = "Осипова Дарья Ивановна",
                            Sex = "Женщина",
                            Speciallity = "Гастроэнтеролог",
                            WorkExperience = 4
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateOnly(1970, 7, 7),
                            Name = "Быкова Вероника Дамировна",
                            Sex = "Женщина",
                            Speciallity = "Гепатолог",
                            WorkExperience = 4
                        });
                });

            modelBuilder.Entity("EternalPeace.Models.MedHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DischargeDate")
                        .HasColumnType("date");

                    b.Property<string>("Diseases")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TreatmentCost")
                        .HasColumnType("numeric");

                    b.Property<int>("WardId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("WardId");

                    b.ToTable("MedHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DischargeDate = new DateOnly(2025, 1, 10),
                            Diseases = "Гастрит",
                            DoctorId = 2,
                            PatientId = 1,
                            RecordDate = new DateOnly(2025, 1, 5),
                            Status = "Выписан",
                            TreatmentCost = 17500m,
                            WardId = 1
                        },
                        new
                        {
                            Id = 2,
                            DischargeDate = new DateOnly(2025, 1, 14),
                            Diseases = "Вирусный Гепатит",
                            DoctorId = 4,
                            PatientId = 2,
                            RecordDate = new DateOnly(2025, 1, 6),
                            Status = "Выписан",
                            TreatmentCost = 35000m,
                            WardId = 4
                        },
                        new
                        {
                            Id = 3,
                            DischargeDate = new DateOnly(2025, 1, 11),
                            Diseases = "Синдром раздражённого кишечника",
                            DoctorId = 2,
                            PatientId = 3,
                            RecordDate = new DateOnly(2025, 1, 6),
                            Status = "Выписан",
                            TreatmentCost = 12000m,
                            WardId = 3
                        },
                        new
                        {
                            Id = 4,
                            DischargeDate = new DateOnly(2025, 1, 16),
                            Diseases = "Камни в желчном пузыре",
                            DoctorId = 2,
                            PatientId = 4,
                            RecordDate = new DateOnly(2025, 1, 6),
                            Status = "Выписан",
                            TreatmentCost = 25000m,
                            WardId = 1
                        },
                        new
                        {
                            Id = 5,
                            DischargeDate = new DateOnly(2025, 1, 13),
                            Diseases = "Жёлтуха",
                            DoctorId = 8,
                            PatientId = 5,
                            RecordDate = new DateOnly(2025, 1, 7),
                            Status = "Выписан",
                            TreatmentCost = 18500m,
                            WardId = 2
                        },
                        new
                        {
                            Id = 6,
                            DischargeDate = new DateOnly(2025, 1, 16),
                            Diseases = "Колит",
                            DoctorId = 7,
                            PatientId = 6,
                            RecordDate = new DateOnly(2025, 1, 9),
                            Status = "Выписан",
                            TreatmentCost = 22000m,
                            WardId = 2
                        },
                        new
                        {
                            Id = 7,
                            DischargeDate = new DateOnly(2025, 1, 14),
                            Diseases = "Инфекционное заболевание почек",
                            DoctorId = 6,
                            PatientId = 7,
                            RecordDate = new DateOnly(2025, 1, 9),
                            Status = "Выписан",
                            TreatmentCost = 20000m,
                            WardId = 1
                        },
                        new
                        {
                            Id = 8,
                            DischargeDate = new DateOnly(2025, 1, 18),
                            Diseases = "Порок сердца",
                            DoctorId = 1,
                            PatientId = 8,
                            RecordDate = new DateOnly(2025, 1, 10),
                            Status = "Выписан",
                            TreatmentCost = 58000m,
                            WardId = 4
                        },
                        new
                        {
                            Id = 9,
                            DischargeDate = new DateOnly(2025, 1, 15),
                            Diseases = "Стеатоз",
                            DoctorId = 4,
                            PatientId = 9,
                            RecordDate = new DateOnly(2025, 1, 10),
                            Status = "Выписан",
                            TreatmentCost = 20000m,
                            WardId = 1
                        },
                        new
                        {
                            Id = 10,
                            DischargeDate = new DateOnly(2025, 1, 16),
                            Diseases = "Гипертония",
                            DoctorId = 1,
                            PatientId = 10,
                            RecordDate = new DateOnly(2025, 1, 11),
                            Status = "Выписан",
                            TreatmentCost = 19500m,
                            WardId = 1
                        },
                        new
                        {
                            Id = 11,
                            DischargeDate = new DateOnly(2025, 1, 20),
                            Diseases = "Ишемическая болезнь сердца",
                            DoctorId = 1,
                            PatientId = 11,
                            RecordDate = new DateOnly(2025, 1, 13),
                            Status = "Выписан",
                            TreatmentCost = 43500m,
                            WardId = 3
                        },
                        new
                        {
                            Id = 12,
                            DischargeDate = new DateOnly(2025, 1, 23),
                            Diseases = "Инфаркт миокарда",
                            DoctorId = 1,
                            PatientId = 12,
                            RecordDate = new DateOnly(2025, 1, 13),
                            Status = "Выписан",
                            TreatmentCost = 120000m,
                            WardId = 5
                        },
                        new
                        {
                            Id = 13,
                            DischargeDate = new DateOnly(2025, 1, 24),
                            Diseases = "Гломерулонефрит",
                            DoctorId = 1,
                            PatientId = 13,
                            RecordDate = new DateOnly(2025, 1, 14),
                            Status = "Выписан",
                            TreatmentCost = 30000m,
                            WardId = 3
                        },
                        new
                        {
                            Id = 14,
                            DischargeDate = new DateOnly(2025, 1, 20),
                            Diseases = "Гастрит",
                            DoctorId = 7,
                            PatientId = 14,
                            RecordDate = new DateOnly(2025, 1, 15),
                            Status = "Выписан",
                            TreatmentCost = 11500m,
                            WardId = 2
                        },
                        new
                        {
                            Id = 15,
                            DischargeDate = new DateOnly(2025, 1, 26),
                            Diseases = "Сердечная недостаточность",
                            DoctorId = 5,
                            PatientId = 15,
                            RecordDate = new DateOnly(2025, 1, 16),
                            Status = "В плате",
                            TreatmentCost = 83000m,
                            WardId = 6
                        },
                        new
                        {
                            Id = 16,
                            DischargeDate = new DateOnly(2025, 1, 23),
                            Diseases = "Нефролитиаз",
                            DoctorId = 6,
                            PatientId = 16,
                            RecordDate = new DateOnly(2025, 1, 18),
                            Status = "Выписан",
                            TreatmentCost = 25000m,
                            WardId = 1
                        },
                        new
                        {
                            Id = 17,
                            DischargeDate = new DateOnly(2025, 1, 26),
                            Diseases = "Пиелонефрит",
                            DoctorId = 5,
                            PatientId = 17,
                            RecordDate = new DateOnly(2025, 1, 19),
                            Status = "В плате",
                            TreatmentCost = 28500m,
                            WardId = 1
                        },
                        new
                        {
                            Id = 18,
                            DischargeDate = new DateOnly(2025, 1, 24),
                            Diseases = "Гастрит",
                            DoctorId = 7,
                            PatientId = 2,
                            RecordDate = new DateOnly(2025, 1, 19),
                            Status = "В плате",
                            TreatmentCost = 10000m,
                            WardId = 2
                        },
                        new
                        {
                            Id = 19,
                            DischargeDate = new DateOnly(2025, 1, 30),
                            Diseases = "Холестаз",
                            DoctorId = 8,
                            PatientId = 18,
                            RecordDate = new DateOnly(2025, 1, 20),
                            Status = "В плате",
                            TreatmentCost = 35000m,
                            WardId = 4
                        },
                        new
                        {
                            Id = 20,
                            DischargeDate = new DateOnly(2025, 1, 28),
                            Diseases = "Гипертония",
                            DoctorId = 5,
                            PatientId = 19,
                            RecordDate = new DateOnly(2025, 1, 21),
                            Status = "В плате",
                            TreatmentCost = 18000m,
                            WardId = 2
                        },
                        new
                        {
                            Id = 21,
                            DischargeDate = new DateOnly(2025, 1, 30),
                            Diseases = "Камни в желчном пузыре",
                            DoctorId = 7,
                            PatientId = 8,
                            RecordDate = new DateOnly(2025, 1, 21),
                            Status = "В плате",
                            TreatmentCost = 45000m,
                            WardId = 2
                        },
                        new
                        {
                            Id = 22,
                            DischargeDate = new DateOnly(2025, 1, 29),
                            Diseases = "Поликистоз почек",
                            DoctorId = 6,
                            PatientId = 20,
                            RecordDate = new DateOnly(2025, 1, 22),
                            Status = "В плате",
                            TreatmentCost = 32500m,
                            WardId = 3
                        },
                        new
                        {
                            Id = 23,
                            DischargeDate = new DateOnly(2025, 1, 27),
                            Diseases = "Инфекционные заболевания почек",
                            DoctorId = 3,
                            PatientId = 5,
                            RecordDate = new DateOnly(2025, 1, 22),
                            Status = "В плате",
                            TreatmentCost = 18500m,
                            WardId = 2
                        },
                        new
                        {
                            Id = 24,
                            DischargeDate = new DateOnly(2025, 1, 30),
                            Diseases = "Язвенная болезнь желудка",
                            DoctorId = 7,
                            PatientId = 6,
                            RecordDate = new DateOnly(2025, 1, 23),
                            Status = "В плате",
                            TreatmentCost = 22500m,
                            WardId = 2
                        },
                        new
                        {
                            Id = 25,
                            DischargeDate = new DateOnly(2025, 1, 30),
                            Diseases = "Гипертония",
                            DoctorId = 1,
                            PatientId = 6,
                            RecordDate = new DateOnly(2025, 1, 23),
                            Status = "В плате",
                            TreatmentCost = 16500m,
                            WardId = 2
                        });
                });

            modelBuilder.Entity("EternalPeace.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("InsuranceExpDate")
                        .HasColumnType("date");

                    b.Property<string>("InsuranceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "102А, Люблинская улица",
                            BirthDate = new DateOnly(1990, 5, 1),
                            InsuranceType = "Полис ОМС",
                            Name = "Иванов Пётр Васильевич",
                            Sex = "Мужчина"
                        },
                        new
                        {
                            Id = 2,
                            Address = "24, Новозаводская улица",
                            BirthDate = new DateOnly(1997, 9, 14),
                            InsuranceType = "Полис ОМС",
                            Name = "Денисова Амина Данииловна",
                            Sex = "Женщина"
                        },
                        new
                        {
                            Id = 3,
                            Address = "47, Деревня Чепелево",
                            BirthDate = new DateOnly(2001, 1, 3),
                            InsuranceExpDate = new DateOnly(2027, 12, 31),
                            InsuranceType = "ДМС",
                            Name = "Лаврентьев Даниил Кириллович",
                            Sex = "Мужчина"
                        },
                        new
                        {
                            Id = 4,
                            Address = "47, 2, Автозаводская улица",
                            BirthDate = new DateOnly(1976, 8, 15),
                            InsuranceType = "Полис ОМС",
                            Name = "Жуков Алексей Матвеевич",
                            Sex = "Мужчина"
                        },
                        new
                        {
                            Id = 5,
                            Address = "21А, проспект 50 лет Октября",
                            BirthDate = new DateOnly(1988, 2, 28),
                            InsuranceType = "Полис ОМС",
                            Name = "Токарева София Тимофеевна",
                            Sex = "Женщина"
                        },
                        new
                        {
                            Id = 6,
                            Address = "40Ж, Проезжая улица",
                            BirthDate = new DateOnly(1993, 6, 11),
                            InsuranceType = "Полис ОМС",
                            Name = "Денисова Амина Данииловна",
                            Sex = "Женщина"
                        },
                        new
                        {
                            Id = 7,
                            Address = "18, улица 1 Мая",
                            BirthDate = new DateOnly(2002, 6, 6),
                            InsuranceType = "Полис ОМС",
                            Name = "Морозов Карим Даниилович",
                            Sex = "Мужчина"
                        },
                        new
                        {
                            Id = 8,
                            Address = "8А, улица Руставели",
                            BirthDate = new DateOnly(1996, 9, 8),
                            InsuranceExpDate = new DateOnly(2025, 12, 31),
                            InsuranceType = "ДМС",
                            Name = "Суслова Полина Дмитриевна",
                            Sex = "Женщина"
                        },
                        new
                        {
                            Id = 9,
                            Address = "28, Пенягинская улица",
                            BirthDate = new DateOnly(2005, 1, 18),
                            InsuranceType = "Полис ОМС",
                            Name = "Крюков Никита Романович",
                            Sex = "Мужчина"
                        },
                        new
                        {
                            Id = 10,
                            Address = "22, Олимпийский проспект",
                            BirthDate = new DateOnly(1977, 8, 29),
                            InsuranceType = "Полис ОМС",
                            Name = "Гусев Михаил Богданович",
                            Sex = "Мужчина"
                        },
                        new
                        {
                            Id = 11,
                            Address = "9, Рябиновая улица",
                            BirthDate = new DateOnly(1999, 3, 22),
                            InsuranceType = "-",
                            Name = "Макаров Марк Макарович",
                            Sex = "Мужчина"
                        },
                        new
                        {
                            Id = 12,
                            Address = "34, проспект 50 лет Октября",
                            BirthDate = new DateOnly(1965, 4, 7),
                            InsuranceType = "Полис ОМС",
                            Name = "Новиков Алексей Артёмович",
                            Sex = "Мужчина"
                        },
                        new
                        {
                            Id = 13,
                            Address = "13, Гончарная улица",
                            BirthDate = new DateOnly(1988, 5, 12),
                            InsuranceExpDate = new DateOnly(2025, 3, 12),
                            InsuranceType = "ДМС",
                            Name = "Дроздов Степан Александрович",
                            Sex = "Мужчина"
                        },
                        new
                        {
                            Id = 14,
                            Address = "11, Коммунистическая улица",
                            BirthDate = new DateOnly(2001, 1, 22),
                            InsuranceType = "Полис ОМС",
                            Name = "Кожевникова Виктория Семёновна",
                            Sex = "Женщина"
                        },
                        new
                        {
                            Id = 15,
                            Address = "9, Рябиновая улица",
                            BirthDate = new DateOnly(1958, 10, 23),
                            InsuranceType = "Полис ОМС",
                            Name = "Никонова Лидия Марковна",
                            Sex = "Женщина"
                        },
                        new
                        {
                            Id = 16,
                            Address = "9, Рябиновая улица",
                            BirthDate = new DateOnly(1959, 7, 1),
                            InsuranceType = "Полис ОМС",
                            Name = "Никонов Павел Витальевич",
                            Sex = "Мужчина"
                        },
                        new
                        {
                            Id = 17,
                            Address = "47, Пенягинская улица",
                            BirthDate = new DateOnly(1973, 11, 15),
                            InsuranceType = "Полис ОМС",
                            Name = "Иванов Федот Павлович",
                            Sex = "Мужчина"
                        },
                        new
                        {
                            Id = 18,
                            Address = "87, Новозаводская улица",
                            BirthDate = new DateOnly(1998, 11, 11),
                            InsuranceExpDate = new DateOnly(2027, 2, 25),
                            InsuranceType = "ДМС",
                            Name = "Гусева Мария Богдановна",
                            Sex = "Женщина"
                        },
                        new
                        {
                            Id = 19,
                            Address = "13, 3-й Железнодорожный тупик",
                            BirthDate = new DateOnly(1988, 4, 27),
                            InsuranceType = "Полис ОМС",
                            Name = "Петрова Мария Алексеевна",
                            Sex = "Женщина"
                        },
                        new
                        {
                            Id = 20,
                            Address = "32, Деревня Чепелево",
                            BirthDate = new DateOnly(2000, 2, 2),
                            InsuranceType = "-",
                            Name = "Орлов Ян Викторович",
                            Sex = "Мужчина"
                        });
                });

            modelBuilder.Entity("EternalPeace.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "O2Esdae1BIpDX7bsgeUv+S1teVqLWpwXBw9qY8l6U7I=",
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "phqK32ADh5Kiy4jmcLIFQKnWwsogSrdU/HaJUOeefTY=",
                            UserName = "User"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "xdfiUTEW4g6lVU5g39FwuyDFDTg6oI/Xe789IXQTncw=",
                            UserName = "User2"
                        });
                });

            modelBuilder.Entity("EternalPeace.Models.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NumBeds")
                        .HasColumnType("integer");

                    b.Property<string>("WardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Wards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumBeds = 4,
                            WardType = "Общая палата"
                        },
                        new
                        {
                            Id = 2,
                            NumBeds = 4,
                            WardType = "Общая палата"
                        },
                        new
                        {
                            Id = 3,
                            NumBeds = 2,
                            WardType = "Двуместная палата"
                        },
                        new
                        {
                            Id = 4,
                            NumBeds = 2,
                            WardType = "Двуместная палата"
                        },
                        new
                        {
                            Id = 5,
                            NumBeds = 1,
                            WardType = "Одноместная палата"
                        },
                        new
                        {
                            Id = 6,
                            NumBeds = 1,
                            WardType = "Одноместная палата"
                        });
                });

            modelBuilder.Entity("EternalPeace.Models.MedHistory", b =>
                {
                    b.HasOne("EternalPeace.Models.Doctor", "Doctor")
                        .WithMany("MedHistories")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EternalPeace.Models.Patient", "Patient")
                        .WithMany("MedHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EternalPeace.Models.Ward", "Ward")
                        .WithMany("MedHistories")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("EternalPeace.Models.Doctor", b =>
                {
                    b.Navigation("MedHistories");
                });

            modelBuilder.Entity("EternalPeace.Models.Patient", b =>
                {
                    b.Navigation("MedHistories");
                });

            modelBuilder.Entity("EternalPeace.Models.Ward", b =>
                {
                    b.Navigation("MedHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
